name: MindBodySoul UI Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'UI/**'
      - '.github/workflows/deploy-ui.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: UI/package-lock.json 

   
      - name: Install dependencies
        working-directory: UI
        run: npm ci --legacy-peer-deps

      - name: Create environemnt file for production
        run: |
          cat > UI/src/environments/environment.production.ts << 'EOF'
          export const environment = {
            production: true,
            apiBaseUrl: 'https://mindbodysoul.onrender.com',
            cloudinary: {
              cloudName: '${{ secrets.CLOUDINARY_CLOUD_NAME }}',
              apiKey: '${{ secrets.CLOUDINARY_API_KEY }}',
              uploadPreset: '${{ secrets.CLOUDINARY_UPLOAD_PRESET }}',
              },
            };
          EOF

          cat > UI/src/environments/environment.ts << 'EOF'
          export const environment = {
          production: false,
            apiBaseUrl: 'http://localhost:5020',
            cloudinary: {
              cloudName: '',
              apiKey: '',
              uploadPreset: '',
              },
            };
          EOF

      - name: Build the Angular app
        working-directory: UI 
        run: npx ng build --configuration production

      - name: Deploy to GitHub Pages
        working-directory: UI
        run: npx angular-cli-ghpages --dir=dist/mind-body-soul
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      