name: MindBodySoul UI Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'UI/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.11.0'
          cache: 'npm'
   
      - name: Install dependencies
        working-directory: UI
        run: npm ci

      - name: Build the Angular app
        working-directory: UI 
        run: ng build --configuration production

      - name: Deploy to GitHub Pages
        working-directory: UI
        run: npx angular-cli-ghpages --dir=dist/mind-body-soul
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      